services:
  controller1:
    container_name: ${COMPOSE_PROJECT_NAME}-controller-1
    image: confluentinc/cp-kafka:${KAFKA_TAG:-latest}
    env_file:
      - ../conf/general/general.env
      - ../conf/general/controller-1.env
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  controller2:
    container_name: ${COMPOSE_PROJECT_NAME}-controller-2
    image: confluentinc/cp-kafka:${KAFKA_TAG:-latest}
    env_file:
      - ../conf/general/general.env
      - ../conf/general/controller-2.env
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  controller3:
    container_name: ${COMPOSE_PROJECT_NAME}-controller-3
    image: confluentinc/cp-kafka:${KAFKA_TAG:-latest}
    env_file:
      - ../conf/general/general.env
      - ../conf/general/controller-3.env
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  broker1:
    container_name: ${COMPOSE_PROJECT_NAME}-broker-1
    image: confluentinc/cp-kafka:${KAFKA_TAG:-latest}
    env_file:
      - ../conf/general/general.env
      - ../conf/general/broker-1.env
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  broker2:
    container_name: ${COMPOSE_PROJECT_NAME}-broker-2
    image: confluentinc/cp-kafka:${KAFKA_TAG:-latest}
    env_file:
      - ../conf/general/general.env
      - ../conf/general/broker-2.env
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  broker3:
    container_name: ${COMPOSE_PROJECT_NAME}-broker-3
    image: confluentinc/cp-kafka:${KAFKA_TAG:-latest}
    env_file:
      - ../conf/general/general.env
      - ../conf/general/broker-3.env
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  ksqldb:
    container_name: ${COMPOSE_PROJECT_NAME}-ksqldb
    image: confluentinc/cp-ksqldb-server:${KAFKA_SQLDB_TAG:-latest}
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - ../conf/general/general.env
      - ../conf/general/ksql.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  mqtt:
    container_name: ${COMPOSE_PROJECT_NAME}-mqtt
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/mosquitto:${MOSQUITTO_TAG:-latest}
    networks:
      - mitra

  tscaledb:
    container_name: ${COMPOSE_PROJECT_NAME}-tscaledb
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/tscaledb:${TSCALEDB_TAG:-latest}
    env_file:
      - ../conf/general/general.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    volumes:
      - /mnt/pg:/mnt/pg
    networks:
      - mitra

  bouncer:
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/bouncer:${BOUNCER_TAG:-latest}
    depends_on:
      tscaledb:
        condition: service_healthy
    env_file:
      - ../conf/general/general.env
    deploy:
      mode: replicated
      replicas: 5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h tscaledb"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

networks:
  mitra:
    name: mitra
